apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-two
  name: hello-world-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-two
  template:
    metadata:
      labels:
        app: hello-world-two
    spec:
      containers:
      - image: cloudacode/hello-go-app:v2.0.0
        name: hello-go-app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi