apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-two
  name: hello-world-two
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-two
  type: NodePort